apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: volume-snapshot-elasticsearch7-master-elasticsearch7-master-1
spec:
  volumeSnapshotClassName: volume-snapclass
  source:
    persistentVolumeClaimName: elasticsearch7-master-elasticsearch7-master-1
