name: Push to repo2

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - stage
    paths-ignore:
      - .github/**

jobs:
  push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repository:
          - repo2
          - repo3

    steps:
      - name: Clone repositories
        run: |
          git clone --branch ${{ github.ref_name }} https://hontarenko:${{ secrets.MERGE }}@github.com/hontarenko/repo1.git &&
          git clone --branch ${{ github.ref_name }} https://hontarenko:${{ secrets.MERGE }}@github.com/hontarenko/repo2.git &&
          git clone --branch ${{ github.ref_name }} https://hontarenko:${{ secrets.MERGE }}@github.com/hontarenko/repo3.git 


      - name: Push to ${{ matrix.repository }}
        run: |

          rsync -avzr --delete --exclude '.git' --exclude '.github' repo1/ ${{ matrix.repository }}/
          cd ${{ matrix.repository }}/ &&
          git config user.name hontarenko &&
          git config user.email hontarenko@amomedia.com &&
          git add -A &&
          git commit -m 'merged upstream' &&
          git push origin ${{ github.ref_name }}
