name: Push to repo2

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #     - stage
  #   paths-ignore:
  #     - .github/**

jobs:
  push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repository:
          - repo2

    steps:
      - uses: actions/checkout@v3.1.0
        with:
          repository: hontarenko/${{ matrix.repository }}
          token: ${{ secrets.MERGE }}
          ref: ${{ github.ref_name }}

      - name: Push to ${{ matrix.repository }}
        run: |
          git config user.email hontarenko@amomedia.com &&
          git config user.name hontarenko &&
          git remote add upstream https://hontarenko:${{ secrets.MERGE }}@github.com/hontarenko/repo1.git &&
          git fetch upstream ${{ github.ref_name }} &&
          git merge --no-edit --no-ff --no-commit --allow-unrelated-histories --strategy-option theirs upstream/${{ github.ref_name }} &&
          git reset HEAD .github &&
          git checkout -- .github &&
          git commit -m 'merged upstream' &&
          git push origin ${{ github.ref_name }}
