name: Push to repo2

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - stage
    paths-ignore:
      - .github/**

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repositories
        run: |
          git clone  https://hontarenko:${{ secrets.MERGE }}@github.com/hontarenko/repo1.git &&
          git clone  https://hontarenko:${{ secrets.MERGE }}@github.com/hontarenko/repo2.git 

      - name: Push to ${{ matrix.repository }}
        run: |

          rsync -avzrh --delete --exclude '.git' --exclude '.github' repo1/ repo2/
          git config user.email hontarenko@amomedia.com &&
          git config user.name hontarenko &&
          cd repo2 &&
          git add -A &&
          git commit -m 'merged upstream' &&
          git push origin ${{ github.ref_name }}
